import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const read = f => readFile(new URL(f, root), 'utf8');
const facade = (await read('src/facade.js')).replace(/^export /gm, '');
const host = (await read('src/host-client.js')).replace('__FACADE__', () => facade).replace('window.__ModuleLoader__.load(', 'captureHost(');
const business = (await read('src/business-client.js')).replace('window.__ModuleLoader__.load(', 'captureBusiness(');
await writeFile(new URL('client.js', root), `// Generated by scripts/build.mjs; source files are in src/.\nwindow.__ModuleLoader__.load({id:'dsh-huaxue-workbench',factory(require){try{\nlet hostDef,businessDef;const captureHost=d=>hostDef=d,captureBusiness=d=>businessDef=d;\n${host}\n${business}\nconst host=hostDef.factory(require),business=businessDef.factory(require);return {name:'dsh-huaxue-workbench',inject:[...new Set([...host.inject,...business.inject])],apply(ctx){try{host.apply(ctx,business);if(typeof business.apply==='function')business.apply(ctx);}catch(error){console.error('HUAXUE_APPLY',error.stack);throw error;}}};}catch(error){console.error('HUAXUE_FACTORY',error.stack);throw error;}\n}});\n`);
console.log('Built standalone client');
